config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/result', to: 'welcome#result', as: 'result_path'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
require 'net/http'


class WelcomeController < ApplicationController
  def index
  end

  def result
    startTime = Time.now
    @url = 'https://gitlab.com'
    @from = "RENNES, FRANCE"
    over = 5*60 # seconds
    @totalRequests = 0
    totalResponseTime = 0
    @requests = Array.new
    while Time.now - startTime <= over do
      start = Time.now
      Net::HTTP.get(URI(@url))
      responseTime = Time.now - start
      @requests.push( responseTime )
      @totalRequests += 1
      totalResponseTime += responseTime 
    end
    @averageResponseTime = totalResponseTime / @totalRequests
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>
<p>Marin ask me "Can you write a small Ruby based script/app that will get HTTP response times over 5 minutes from your location to https://gitlab.com?"</p>
<p>This is this small Ruby based script/app!</p>
<p>I choose a rails app in order that Marin can get result from my location Rennes, FRANCE</p>
<p><%= link_to 'Generate requests to https://gitlab.com and see reponse time', result_path_url %></p>
<p><a href="mailto:victor@hakoun.fr">Victor Hakoun</a></p>

app/views/welcome/result.html.erb
<h1>Listing HTTP GET response times over 5 minutes from <%= @from %> to <%= @url %></h1>
<p><%= @totalRequests %> requests response in average <%= @averageResponseTime %> s</p>
 
<table>
  <tr>
    <th>Request number</th>
    <th>Response time</th>
  </tr>
 
  <% @requests.each_with_index do |request, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= request %></td>
    </tr>
  <% end %>
</table>